### ISSUE TITLE
TypeError: Only absolute URLs are supported

### ISSUE THREAD

**Issue by maxijabase** [hygraph/hygraph-sveltekit-portfolio-and-blog-starter#15]
When following the instructions to build this starter locally, once I do `pnpm i` and `pnpm dev` I get:
```
PS C:\Users\Maxi\Documents\GitHub\maxijabase.dev> pnpm dev

> developer-portfolio-and-blog@0.0.1 dev C:\Users\Maxi\Documents\GitHub\maxijabase.dev
> vite dev

Your jsconfig.json should extend the configuration generated by SvelteKit:
{
  "extends": "./.svelte-kit/tsconfig.json"
}

  VITE v3.0.3  ready in 548 ms

  ➜  Local:   http://127.0.0.1:5173/
  ➜  Network: use --host to expose

C:\Users\Maxi\Documents\GitHub\maxijabase.dev\node_modules\.pnpm\node-fetch@2.6.1\node_modules\node-fetch\lib\index.js:1305
                throw new TypeError('Only absolute URLs are supported');
                      ^

TypeError: Only absolute URLs are supported
    at getNodeRequestOptions (C:\Users\Maxi\Documents\GitHub\maxijabase.dev\node_modules\.pnpm\node-fetch@2.6.1\node_modules\node-fetch\lib\index.js:1305:9)
    at C:\Users\Maxi\Documents\GitHub\maxijabase.dev\node_modules\.pnpm\node-fetch@2.6.1\node_modules\node-fetch\lib\index.js:1410:19
    at new Promise (<anonymous>)
    at fetch (C:\Users\Maxi\Documents\GitHub\maxijabase.dev\node_modules\.pnpm\node-fetch@2.6.1\node_modules\node-fetch\lib\index.js:1407:9)
    at fetch (C:\Users\Maxi\Documents\GitHub\maxijabase.dev\node_modules\.pnpm\cross-fetch@3.1.4\node_modules\cross-fetch\dist\node-ponyfill.js:10:20)
    at C:\Users\Maxi\Documents\GitHub\maxijabase.dev\node_modules\.pnpm\graphql-request@4.0.0_graphql@16.3.0\node_modules\graphql-request\dist\index.js:164:42
    at step (C:\Users\Maxi\Documents\GitHub\maxijabase.dev\node_modules\.pnpm\graphql-request@4.0.0_graphql@16.3.0\node_modules\graphql-request\dist\index.js:63:23)
    at Object.next (C:\Users\Maxi\Documents\GitHub\maxijabase.dev\node_modules\.pnpm\graphql-request@4.0.0_graphql@16.3.0\node_modules\graphql-request\dist\index.js:44:53)
    at C:\Users\Maxi\Documents\GitHub\maxijabase.dev\node_modules\.pnpm\graphql-request@4.0.0_graphql@16.3.0\node_modules\graphql-request\dist\index.js:38:71
    at new Promise (<anonymous>)
 ELIFECYCLE  Command failed with exit code 1.
```

**Comment by maxijabase** [comment]
I managed to get around this by cloning @oliverjohns's [fork of this template](https://github.com/oliverjohns/hygraph-sveltekit-portfolio-and-blog-starter), and updating packages with `pnpm update`. After doing `pnpm i` and `pnpm dev`, it boots up properly. @tomgenoni @ronakganatra

**Comment by jpedroschmitz** [comment]
Thanks, @oliverjohns, for working on this update! We released a new version, and it's working now! 🎉
