### ISSUE TITLE
Only Absolute URLs are Supported

### ISSUE THREAD

**Issue by AttackOnSight** [hygraph/hygraph-sveltekit-portfolio-and-blog-starter#6]
Following the tutorial but getting this error after adding the first two scripts to `/src/routes/index.svelte` and using `npm run dev` in the tutorial.

```
Only absolute URLs are supported
TypeError: Only absolute URLs are supported
    at getNodeRequestOptions (C:\Users\***\my-developer-portfolio\node_modules\node-fetch\lib\index.js:1327:9)
    at C:\Users\node_modules\node-fetch\lib\index.js:1440:19
    at new Promise (<anonymous>)
    at fetch (C:\Users\***\my-developer-portfolio\node_modules\node-fetch\lib\index.js:1437:9)
    at fetch (C:\Users\***\my-developer-portfolio\node_modules\cross-fetch\dist\node-ponyfill.js:10:20)
    at C:\Users\***\my-developer-portfolio\node_modules\graphql-request\dist\index.js:166:42
    at step (C:\Users\***\my-developer-portfolio\node_modules\graphql-request\dist\index.js:63:23)
    at Object.next (C:\Users\***\my-developer-portfolio\node_modules\graphql-request\dist\index.js:44:53)
    at C:\Users\***\my-developer-portfolio\node_modules\graphql-request\dist\index.js:38:71
    at new Promise (<anonymous>)

```

The LocalHost then displays an error 500 with the above shown. 

Can anyone please help?

**Comment by EmmanuelPallares** [comment]
> 

I solved this log with adding environment variables directly on production site. Vercel. While I worked in local host this log only shows when I opened the codespaces and normal studio code at same time. Check another instance and make absolute url and not undefined or null

**Comment by jpedroschmitz** [comment]
You need to add the environment variables to the project. If you already have them on Vercel, you can run `vercel link` and then `vercel env pull`.
